version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5002:5000"
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3002:3000"
    depends_on:
      - backend
