apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000       # Port inside the cluster
      targetPort: 5000 # Port your backend container listens on
  type: ClusterIP     # Internal access only
